---
- name: Debian...
  when: ansible_os_family == 'Debian' and not emacs_build_from_src
  include: Debian.yml

- name: Fedora
  when: ansible_distribution == 'Fedora' and not emacs_build_from_src
  include: Fedora.yml

- name: EL
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora' and not emacs_build_from_src
  include: EL.yml

